sink("/Users/nischay92/Documents/CNS_SRES_1/backend/r_script_debug.txt")
cat("📂 Working Directory:\n", getwd(), "\n\n")
cat("📁 Files in current directory:\n", list.files(), "\n\n")
cat("🔍 Session Info:\n")
print(sessionInfo())
sink()

png("/Users/nischay92/Documents/CNS_SRES_1/backend/static/plots/6ce40858-b5a0-4d3d-895c-813d7f853933.png")
fig <- plot_ly(z = ~volcano, type = 'surface')
dev.off()